export enum RequiredText {
    NAME = 'Please enter a name',
    SURNAME = 'Please enter a surname',
    PASSWORD = 'Please enter a password',
    AGENCY = 'Please enter an agency',
    TITLE = 'Please enter a title',
    FULL_TITLE = 'Please enter a full title',
    SHORTCODE = 'Please enter a shortcode',
    CODE = 'Please enter a code',
    STATE = 'Please enter a state',
    DEPARTMENT = 'Please enter a department',
    LOCATION_STR = 'Please enter a location str',
    COUNTRY = 'Please enter a country',
    COUNTRY_CODE = 'Please enter a country code',
    REGION = 'Please enter a region',
    REGION_CODE = 'Please enter a region code',
    CITY = 'Please enter a city',
    ZIP_CODE = 'Please enter a zip code',
}
