export enum MimeTypes {
  png = 'image/png',
  jpeg = 'image/jpeg',
  heic = 'image/heic',
  dng = 'image/x-adobe-dng',
  gif = 'image/gif',
  avi = 'video/x-msvideo',
  avi_old = 'video/avi',
  flv = 'video/x-flv',
  mkv = 'video/x-matroska',
  mov = 'video/quicktime',
  mp4 = 'video/mp4',
  mpeg = 'video/mpeg',
  ogg = 'video/ogg',
  webm = 'video/webm',
  wmv = 'video/x-ms-wmv',
}
