export const DATE_FORMAT = 'YYYY.MM.DD'
export const DATE_TIME_FORMAT = 'YYYY.MM.DD HH:mm:ss'
export const DEFAULT_TIME_STAMP = '00:00:00.000'
export const EXIF_DATE_TIME_FORMAT = 'YYYY:MM:DD HH:mm:ss'
// export const DATE_ISO_FORMAT_WITHOUT_TIME_ZONE = 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'
export const INVALID_DATE = 'Invalid Date'
